# Generated by Django 4.2.3 on 2023-09-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_amount', models.IntegerField()),
                ('payment_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentelAccounts',
            fields=[
                ('rentel_account_number', models.AutoField(primary_key=True, serialize=False)),
                ('security_deposit', models.IntegerField()),
                ('total_rent', models.IntegerField()),
                ('balance_rent', models.IntegerField(default=models.IntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='Reservaltion',
            fields=[
                ('reservation_number', models.AutoField(primary_key=True, serialize=False)),
                ('reserve_from', models.DateField(auto_now=True)),
                ('reserve_to', models.DateField()),
                ('renting_status', models.BooleanField(default=False)),
            ],
        ),
    ]
