# Generated by Django 4.2.3 on 2023-09-12 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicles_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservaltion',
            fields=[
                ('reservation_number', models.AutoField(primary_key=True, serialize=False)),
                ('reserve_from', models.DateField(auto_now=True)),
                ('reserve_to', models.DateField()),
                ('renting_status', models.BooleanField(default=False)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myvehicle_reservations', to=settings.AUTH_USER_MODEL)),
                ('renting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to='vehicles.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='RentelAccounts',
            fields=[
                ('rentel_account_number', models.AutoField(primary_key=True, serialize=False)),
                ('security_deposit', models.IntegerField()),
                ('total_rent', models.IntegerField()),
                ('balance_rent', models.IntegerField(default=models.IntegerField())),
                ('reservation_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.reservaltion')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_amount', models.IntegerField()),
                ('payment_date', models.DateField(auto_now=True)),
                ('rentel_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payment_list', to='renting.rentelaccounts')),
            ],
        ),
    ]
