# Generated by Django 4.2.3 on 2023-09-16 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaltion',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myvehicle_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaltion',
            name='renting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaltion',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_list', to='vehicles.vehicles'),
        ),
        migrations.AddField(
            model_name='rentelaccounts',
            name='reservation_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.reservaltion'),
        ),
        migrations.AddField(
            model_name='rentalpayments',
            name='rentel_account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payment_list', to='renting.rentelaccounts'),
        ),
    ]
