# Generated by Django 4.2.3 on 2023-07-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_accounts',
            fields=[
                ('rental_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_deposit', models.IntegerField(default=2000)),
                ('total_rent', models.IntegerField()),
                ('balance_rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserve_from', models.DateField()),
                ('reserve_to', models.DateField()),
                ('request_status', models.BooleanField(default=False)),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user_id', to=settings.AUTH_USER_MODEL)),
                ('requested_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user_id', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_reviews',
            fields=[
                ('rental_reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('commented_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user_id', to=settings.AUTH_USER_MODEL)),
                ('commenter_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter_user_id', to=settings.AUTH_USER_MODEL)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_payments',
            fields=[
                ('rental_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_amount', models.IntegerField()),
                ('rental_payment_date', models.DateField(auto_now_add=True)),
                ('rent_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.rental_accounts')),
            ],
        ),
        migrations.AddField(
            model_name='rental_accounts',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.reservation'),
        ),
        migrations.AddField(
            model_name='rental_accounts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
