# Generated by Django 4.2.3 on 2023-07-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_category',
            fields=[
                ('vehicle_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_category', models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('THREE_WHEELER', 'Three Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('HEAVY_VEHICLE', 'Heavy Vehicle')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_company',
            fields=[
                ('vehicle_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_model',
            fields=[
                ('vehicle_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model_name', models.CharField(max_length=50)),
                ('vehicle_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_company')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_sub_category',
            fields=[
                ('vehicle_sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_sub_category', models.CharField(choices=[('CYCLE', 'Cycle'), ('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('BUS', 'Bus'), ('AUTO', 'Auto'), ('TRUCK', 'Truck'), ('LORRY', 'Lorry')], max_length=30)),
                ('vehicle_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_category')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=50, unique=True)),
                ('available_from', models.DateField(auto_now_add=True)),
                ('available_to', models.DateField(auto_now_add=True)),
                ('rent', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_model')),
                ('vehicle_sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle_model',
            name='vehicle_sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_sub_category'),
        ),
        migrations.CreateModel(
            name='Vehicle_images',
            fields=[
                ('vehicles_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicle_images')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_model')),
            ],
        ),
    ]
