# Generated by Django 4.2.3 on 2023-08-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='vehicle_sub_category_id',
        ),
        migrations.AddField(
            model_name='vehicle_model',
            name='color',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle_category',
            name='vehicle_category',
            field=models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('THREE_WHEELER', 'Three Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('HEAVY_VEHICLE', 'Heavy Vehicle'), ('OTHER_VEHICLE', 'Other Vehicle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle_sub_category',
            name='vehicle_sub_category',
            field=models.CharField(choices=[('CYCLE', 'Cycle'), ('BIKE', 'Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('BUS', 'Bus'), ('AUTO', 'Auto'), ('TRUCK', 'Truck'), ('LORRY', 'Lorry'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='available_to',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
