# Generated by Django 4.2.3 on 2023-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
