# Generated by Django 4.2.3 on 2023-08-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_transaction',
            name='wallet_transaction_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
